---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.11.1
  creationTimestamp: null
  name: jobruns.neosync.dev
spec:
  group: neosync.dev
  names:
    kind: JobRun
    listKind: JobRunList
    plural: jobruns
    singular: jobrun
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: JobRun is the Schema for the jobruns API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: JobRunSpec defines the desired state of JobRun
            properties:
              runConfig:
                properties:
                  benthos:
                    properties:
                      configFrom:
                        properties:
                          secretKeyRef:
                            properties:
                              key:
                                type: string
                              name:
                                type: string
                            required:
                            - key
                            - name
                            type: object
                        required:
                        - secretKeyRef
                        type: object
                    required:
                    - configFrom
                    type: object
                required:
                - benthos
                type: object
            required:
            - runConfig
            type: object
          status:
            description: JobRunStatus defines the observed state of JobRun
            properties:
              jobStatus:
                description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                  of cluster Important: Run "make" to regenerate code after modifying
                  this file'
                properties:
                  active:
                    description: The number of pending and running pods.
                    format: int32
                    type: integer
                  completedIndexes:
                    description: CompletedIndexes holds the completed indexes when
                      .spec.completionMode = "Indexed" in a text format. The indexes
                      are represented as decimal integers separated by commas. The
                      numbers are listed in increasing order. Three or more consecutive
                      numbers are compressed and represented by the first and last
                      element of the series, separated by a hyphen. For example, if
                      the completed indexes are 1, 3, 4, 5 and 7, they are represented
                      as "1,3-5,7".
                    type: string
                  completionTime:
                    description: Represents time when the job was completed. It is
                      not guaranteed to be set in happens-before order across separate
                      operations. It is represented in RFC3339 form and is in UTC.
                      The completion time is only set when the job finishes successfully.
                    format: date-time
                    type: string
                  conditions:
                    description: 'The latest available observations of an object''s
                      current state. When a Job fails, one of the conditions will
                      have type "Failed" and status true. When a Job is suspended,
                      one of the conditions will have type "Suspended" and status
                      true; when the Job is resumed, the status of this condition
                      will become false. When a Job is completed, one of the conditions
                      will have type "Complete" and status true. More info: https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/'
                    items:
                      description: JobCondition describes current state of a job.
                      properties:
                        lastProbeTime:
                          description: Last time the condition was checked.
                          format: date-time
                          type: string
                        lastTransitionTime:
                          description: Last time the condition transit from one status
                            to another.
                          format: date-time
                          type: string
                        message:
                          description: Human readable message indicating details about
                            last transition.
                          type: string
                        reason:
                          description: (brief) reason for the condition's last transition.
                          type: string
                        status:
                          description: Status of the condition, one of True, False,
                            Unknown.
                          type: string
                        type:
                          description: Type of job condition, Complete or Failed.
                          type: string
                      required:
                      - status
                      - type
                      type: object
                    type: array
                    x-kubernetes-list-type: atomic
                  failed:
                    description: The number of pods which reached phase Failed.
                    format: int32
                    type: integer
                  ready:
                    description: "The number of pods which have a Ready condition.
                      \n This field is beta-level. The job controller populates the
                      field when the feature gate JobReadyPods is enabled (enabled
                      by default)."
                    format: int32
                    type: integer
                  startTime:
                    description: Represents time when the job controller started processing
                      a job. When a Job is created in the suspended state, this field
                      is not set until the first time it is resumed. This field is
                      reset every time a Job is resumed from suspension. It is represented
                      in RFC3339 form and is in UTC.
                    format: date-time
                    type: string
                  succeeded:
                    description: The number of pods which reached phase Succeeded.
                    format: int32
                    type: integer
                  uncountedTerminatedPods:
                    description: "UncountedTerminatedPods holds the UIDs of Pods that
                      have terminated but the job controller hasn't yet accounted
                      for in the status counters. \n The job controller creates pods
                      with a finalizer. When a pod terminates (succeeded or failed),
                      the controller does three steps to account for it in the job
                      status: (1) Add the pod UID to the arrays in this field. (2)
                      Remove the pod finalizer. (3) Remove the pod UID from the arrays
                      while increasing the corresponding counter. \n Old jobs might
                      not be tracked using this field, in which case the field remains
                      null."
                    properties:
                      failed:
                        description: Failed holds UIDs of failed Pods.
                        items:
                          description: UID is a type that holds unique ID values,
                            including UUIDs.  Because we don't ONLY use UUIDs, this
                            is an alias to string.  Being a type captures intent and
                            helps make sure that UIDs and names do not get conflated.
                          type: string
                        type: array
                        x-kubernetes-list-type: set
                      succeeded:
                        description: Succeeded holds UIDs of succeeded Pods.
                        items:
                          description: UID is a type that holds unique ID values,
                            including UUIDs.  Because we don't ONLY use UUIDs, this
                            is an alias to string.  Being a type captures intent and
                            helps make sure that UIDs and names do not get conflated.
                          type: string
                        type: array
                        x-kubernetes-list-type: set
                    type: object
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
