## Append samples you want in your CSV to this file as resources ##
resources:
- _v1alpha1_connection.yaml
- _v1alpha1_job.yaml
- _v1alpha1_jobrun.yaml
- _v1alpha1_sqlconnection.yaml
- _v1alpha1_jobruntask.yaml
- _v1alpha1_task.yaml
- _v1alpha1_jobconfig.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
