on:
  pull_request:
    paths:
      - frontend/**

name: Lint
jobs:
  # knip:
  #   name: Knip
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Set up Node
  #       uses: actions/setup-node@v3

  #     - run: npm ci
  #     - run: npm run knip:production

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: frontend

      - run: npm ci
      - run: npm run prettier:check
