apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "neosync-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- if eq .Values.datadog.enabled true }}
    tags.datadoghq.com/env: {{ .Values.nucleusEnv }}
    tags.datadoghq.com/service: {{ template "neosync-app.fullname" . }}
    tags.datadoghq.com/version: {{ .Values.image.tag | default .Chart.AppVersion  }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ template "neosync-app.fullname" . }}
  replicas: 1
  template:
    metadata:
      annotations:
        {{- if eq .Values.datadog.enabled true }}
        ad.datadoghq.com/nucleus-api.logs: '[{"source":"nucleus-neosync-app","service":"{{ template "neosync-app.fullname" . }}"}]'
        {{- end }}
        {{- if eq .Values.istio.enabled true }}
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
        {{- end }}
        rollme: {{ randAlphaNum 5 | quote }} # causes deployment to always roll on helm upgrade
      labels:
        app: {{ template "neosync-app.fullname" . }}
        version: v1
        {{- if eq .Values.istio.enabled true }}
        sidecar.istio.io/inject: "true"
        {{- end }}
        {{- if eq .Values.datadog.enabled true }}
        admission.datadoghq.com/enabled: "true"
        tags.datadoghq.com/env: {{ .Values.nucleusEnv }}
        tags.datadoghq.com/service: {{ template "neosync-app.fullname" . }}
        tags.datadoghq.com/version: {{ .Values.image.tag | default .Chart.AppVersion  }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "neosync-app.serviceAccountName" . }}
      {{- end }}
      terminationGracePeriod: {{ .Values.terminationGracePeriod }}

      containers:
        - name: user-container
          image: '{{ .Values.image.repository | default "ghcr.io/nucleuscloud/neosync-app" }}:{{ .Values.image.tag | default .Chart.AppVersion  }}'
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
              name: http
              protocol: TCP
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP

            {{- if eq .Values.datadog.enabled true }}
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
            {{- end }}

          envFrom:
            - secretRef:
                name: {{ template "neosync-app.fullname" . }}-service-evs
          # {{- if eq .Values.nucleusEnv "dev" }} # config created by Tilt; keep this at the bottom to override
          #   - configMapRef:
          #       name: dev-config
          # {{- end }}
